---
#
# typical run:
#
# ansible-playbook -i env/<ENVIRONMENT> gpio-trigger.yml
#
#

- name: Install prerequisite software
  hosts: my_pi
  gather_facts: false
  tags: [ prerequisite_software ]

  vars:

    debian_packages:
      - python3
      - python3-pip

    python_packages:
      - RPi.GPIO

  tasks:

    - name: "Run apt-get update if cache is older than a week"
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 604800 # 1 week = 7 * 24 * 3600 seconds

    - name: "Install prerequisite debian packages"
      become: yes
      apt:
        name: "{{ debian_packages }}"

    - name: "Install prerequisite pip packages"
      become: yes
      pip:
        name: "{{ python_packages }}"
        executable: pip3


- name: Install gpio-trigger as systemd service
  hosts: my_pi
  gather_facts: false
  tags: [ systemd ]

  vars:
    systemd_service_template: "gpio-trigger.service.j2"
    gpio_trigger_executable: "/home/volumio/devel/gpio-trigger/gpio-trigger.py"

  roles:
    - name: systemd
      systemd_service: "gpio-trigger-volumio-next"
      gpio_trigger_command: "{{ gpio_trigger_executable }} 13 curl 'http://localhost:3000/api/v1/commands/?cmd=next'"

    - name: systemd
      systemd_service: "gpio-trigger-pi-shutdown"
      gpio_trigger_command: "{{ gpio_trigger_executable }} 5 command 'shutdown -h now'"


  handlers:

    - name: Restart systemd services
      systemd:
        name: "{{ item }}.service"
        state: restarted
      become: yes
      loop:
        - gpio-trigger-volumio-next
        - gpio-trigger-pi-shutdown
